### ISSUE TITLE
[front-end] redux 사용해보기

### ISSUE THREAD

**Issue by MinSikSon** [ara-official/ARA#16]
* store
* container
* 등등 사용해보기

**Comment by jaehunchoi** [comment]
**리덕스 조건**
1. 하나의 애플리케이션 안에는 하나의 스토어가 있습니다.
2. 상태는 읽기전용 입니다.	
	- 불변성 유지를 해야함 이 유지를 위해 **immutable**사용
3. 변화를 일으키는 함수, 리듀서는 순수한 함수여야 합니다.
	- 같은input이라면 항상 **output 같아야함** output이 다른 경우라면 **리덕스 미들웨어 를 사용**

**컨테이너 컴포넌**트 : 리덕스와 연동된 컴포넌트
**프리젠테이셔널 컴포넌트** : 단순히 뷰 만을 보여주기 위하여 만들어진 컴포넌트
**module** : 액션과 리듀서를 기능별로 분류하여 작성한 하나의 파일
	ex) 카운터에 관련된 코드는 counter.js 에서 작성하고, 투두리스트에 관련된건 todo.js 에 작성

**configure.js** 는 리덕스 스토어를 생성하는 함수를 모듈화하여 내보내는 역할
	이유 : 서버쪽에서도 각 요청이 처리 될 때마다 스토어를 생성해주어야 하는데요, 그런 작업을 하게 될 때 이렇게 스토어를 생성하는 함수를 이렇게 모듈화

**store/index.js** 에선 스토어를 생성한다음에 내보내고, 이렇게 모듈화된 스토어는 브라우저쪽에서만 사용되는 스토어이다.


**actionCreators.js** 에서도 스토어를 불러오고, 또 각 모듈들에서 선언 했던 액션 생성함수들을 불러와서 store 의 dispatch 와 미리 바인딩 작업


**Ducks 구조** : 액션과 리듀서를 하나의 파일에 작성 - 실제 리액트 매뉴얼은 각각 다른 파일에 작성이긴하다.
-------------------------------------------------------------------------------------------------
**redux-actions 의 createAction 이라는 함수**를 사용하면 액션 생성 함수 코드를 다음과 같이 작성가능


**전**
// 액션 타입을 정의해줍니다.
const INCREMENT = 'counter/INCREMENT';
const DECREMENT = 'counter/DECREMENT';

// 액션 생성 함수를 만듭니다.
// 이 함수들은 나중에 다른 파일에서 불러와야 하므로 내보내줍니다.
export const increment = () => ({ type: INCREMENT });
export const decrement = () => ({ type: DECREMENT });


**후**
import { createAction } from 'redux-actions';

// 액션 타입을 정의해줍니다.
const INCREMENT = 'counter/INCREMENT';
const DECREMENT = 'counter/DECREMENT';

// 액션 생성 함수를 만듭니다.
export const increment = createAction(INCREMENT);
export const decrement = createAction(DECREMENT);



----------------------------------------------------------------

**handleActions 를 사용하면, 리듀서 코드를 조금 더 깔끔하게 작성**
**전**
export default function reducer(state = initialState, action) {
  // 리듀서 함수에서는 액션의 타입에 따라 변화된 상태를 정의하여 반환합니다.
  // state = initialState 이렇게 하면 initialState 가 기본 값으로 사용됩니다.
  switch(action.type) {
    case INCREMENT:
      return { number: state.number + 1 };
    case DECREMENT:
      return { number: state.number - 1 };
    default:
      return state; // 아무 일도 일어나지 않으면 현재 상태를 그대로 반환합니다.
  }
}
**후**
export default handleActions({
  [INCREMENT]: (state, action) => {
    return { number: state.number + 1 };
  },
  // action 객체를 참조하지 않으니까 이렇게 생략을 할 수도 있겠죠?
  // state 부분에서 비구조화 할당도 해주어서 코드를 더욱 간소화시켰습니다.
  [DECREMENT]: ({ number }) => ({ number: number - 1 })
}, initialState);
--------------------------------------------------------------------------------------------

**루트 리듀서** : 여러개의 리듀서가 존재 할 때에는, redux 의 함수 combineReducers 를 사용하여 하나의 리듀서로 합쳐주는 역할 

예시
import { combineReducers } from 'redux';
import counter from './counter';

export default combineReducers({
  counter
});


**만약에 리듀서가 늘어나면 combineReducers({}) 부분에 더 추가 필요.**



--------------------------------------------------------------------------------------------
